package com.mobile.collective.client_server;

/**
 * Created by Robin on 14.02.2016.
 */
public enum HttpType {
    REGISTER, LOGIN, CHANGEPASSWORD, GETTASKS, ADDTASK, APPROVETASK, DISAPPROVETASK, DOTASK, TASKHISTORY, DELETETASK, EDITTASK, GETFEEDHISTORY, GETSCORES, EDITFLAT, GETFLATSETTINGS
}
